### ISSUE TITLE
Making the Freesurfer input optional

### ISSUE THREAD

**Issue by amnsbr** [brainlife/app-fmriprep#14]
Is it possible to make the Freesurfer input optional? I understand that even when we are not going to use the surface output, fmrirprep will use the Freesurfer output to optimize e.g., creating the brain mask or brain registration. But it would be great if we could have the option of using fmriprep without the need for the Freesurfer input (with the --fs-no-reconall flag).

**Comment by faskowit** [comment]
this could be an easy change at the code-level... however, for the interaction with the brainlife interface it is a bit more tricky.  We tried to constrain the input choices to make the app map from specific inputs to specific outputs... this makes the brainlife app more simple to manage. introducing variable inputs that could/could not produce certain outputs creates more headaches at the app level, if that makes sense.   But perhaps soichi could chime in too.

**Comment by soichih** [comment]
Yes, making freesurfer optional makes it a bit tricky to distinguish use cases where user wants fmriprep itself to run freesurfer OR not running freesurfer at all (and set --fs-no-reconall option). I didn't quite understand what "--fs-no-reconall" did, but if fmriprep can entirely skip using freesurfer, we could just set --fs-no-reconall if freesurfer is not fed? I always thought that freesurfer was a critical input for fmriprep to work at all, but is this not the case?

**Comment by faskowit** [comment]
in my opinion, I do think that the FreeSurfer input is critical, as it helps to refine the masks applied to the anatomical and functional data (my understanding based on documentation... would have to check code for exactly the case).

**Comment by amnsbr** [comment]
Thank you for your quick replies. Yes that would probably be difficult for users and perhaps not possible under the brainlife framework. Alternatively maybe I can fork this app and modify it to create a private app for my project that does not use Freesurfer, provided that I would be able to register the app. @soichih Yes it is possible to skip Freesurfer functionalities in fmriprep by using "--fs-no-reconall" ([ref](https://fmriprep.org/en/stable/workflows.html#surface-preprocessing)). Nevertheless, you would still need to provide the Freesurfer license to the fmriprep. Here's an example I have recently used in a project (and it worked very well):
```
docker run -ti --rm \
    -v $HOME/Vicar/data-BIDS:/data:ro \
    -v $HOME/Vicar/data-BIDS/derivatives:/out \
    -v $HOME/Vicar/fmriprep_workdir:/work \
	-v /usr/local/freesurfer_dev/license.txt:/opt/freesurfer/license.txt \
    poldracklab/fmriprep \
    /data /out/fmriprep \
    participant \
    -w /work \
    --nthreads 3 \
    --mem_mb 6000 \
    --low-mem \
    --bold2t1w-dof 12 \
    --fs-no-reconall \
    --write-graph \
    --verbose
```

**Comment by amnsbr** [comment]
I'm not sure how okay it is to skip it, but fmriprep works without Freesurfer input, and the quality of the output (masks and registration) looked alright to me.

> in my opinion, I do think that the FreeSurfer input is critical, as it helps to refine the masks applied to the anatomical and functional data (my understanding based on documentation... would have to check code for exactly the case).

**Comment by soichih** [comment]
@effigies Could you comment on the importance of freesurfer for fmriprep? I am guessing that the existence of `--fs-no-reconall` indicates that freesurfer input is more optional than we originally thought? 

We could make freesurfer optional, and add an *advanced* option to "skip freesurfer preprocessing". If user doesn't check this check box and not feed freesurfer input, we can make the fail to fail even though the freesurfer input is optional for our App?

**Comment by effigies** [comment]
FreeSurfer dramatically improves BOLD-T1w registration and enables sampling functional data to surfaces, including the fsLR mesh, and a refinement of the brain mask, but we do have fallback behaviors that predate the inclusion of FreeSurfer.

We strongly recommend using FreeSurfer, but with the presence of the fallbacks we haven't deprecated it. If it becomes a significant maintenance burden, we might in the future, but it hasn't thus far.

I haven't fully processed this discussion, so apologies if I'm saying something obvious, but my instinct would be:

1) FreeSurfer input, use FreeSurfer.
2) No FreeSurfer input, run FreeSurfer (or error, if it's not worth dealing with an additional output dir).
3) FreeSurfer input + `--fs-no-reconall`: Error (I don't know what you want)
4) No FreeSurfer input + `--fs-no-reconall`, skip FreeSurfer.

**Comment by faskowit** [comment]
thanks @effigies.  given this extra info... I think its worth enforcing FreeSurfer for brainlife users, which will be running fmriprep on a wide range of input mri. in my mind, the most reconstruction info, the better!

**Comment by soichih** [comment]
@amnsbr Is the reason why you don't want to run freesurfer simply to save time for your preprocessing? Or is there other more technical reason? 

By the way, although fmriprep might not need freesurfer, there are many other BL Apps that require freesurfer, so I think it's good to have freesurfer available in case you might want to run other BL Apps.

**Comment by amnsbr** [comment]
@faskowit That's right, thank you very much. 
@soichih Yes, I have 355 subjects and I decided not to run Freesurfer mainly to save time on my end and resources on BL's end, under the impression that Freesurfer does not add much to volume-based preprocessing of fMRI images. But now I understand that using Freesurfer is actually an important default behavior of fmriprep and I'm going to run the current version with Freesurfer. Thanks.
